### ISSUE TITLE
Adjacent polygons are returned from search api

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#259]
From Candace C
>A search on UIC facility polygons based on Salt Lake County includes polygons that share the Salt Lake County boundary.  For example, 'Davis County MS4' is included in the search result as shown in the following screen shot
>![image](https://cloud.githubusercontent.com/assets/1326248/4939821/b72f5912-65d5-11e4-9c25-e8525b5b63c4.png)

**Comment by stdavis** [comment]
Before giving an estimate on this one @steveoh and I would have to brainstorm some work-arounds and get one approved with Candace.

**Comment by stdavis** [comment]
@steveoh I'd like to brainstorm on this next week when you have a minute.

**Comment by hsandbeck** [comment]
When you get a moment call me at 8015364152

On Fri, Feb 5, 2016 at 10:04 AM, Scott Davis <notifications@github.com>
wrote:

> @steveoh <https://github.com/steveoh> I'd like to brainstorm on this next
> week when you have a minute.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/deq-enviro/issues/259#issuecomment-180442646>.
>



-- 
Harold Sandbeck
Environmental Scientist/GIS Specialist
Division of Environmental Response and Remediation
Work Phone (801) 536-4152
Work Fax Number (801) 536-4242
haroldsandbeck@utah.gov

**Comment by stdavis** [comment]
OK. I've come up with a possible solution to this issue. What about creating a tolerance for polygon searches? So if a feature only overlaps the search polygon by a distance less than the tolerance it is not returned? Here's an example of what Candace's query above looks like with a 250 meter tolerance:
![image](https://cloud.githubusercontent.com/assets/1326248/12989246/d891ac1a-d0c1-11e5-9209-cc11d44abec3.png)

It still selects all of the polygons that are within the county including the one that is the same basic shape as the county but doesn't select the ones in Utah and Davis county.

This tolerance would only apply when you are searching a polygon layer. Searches on point and line datasets would be unaffected.

@steveoh, @hsandbeck Can you think of any reason why this shouldn't work?

**Comment by stdavis** [comment]
Here's what the code looks like: https://github.com/agrc/deq-enviro/commit/fa512dfe5a74846bd1520b009059a724b4bdfa65

**Comment by steveoh** [comment]
lgtm
