### ISSUE TITLE
Limit Search API Return Records

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#290]
Most of the datasets for this application are relatively small. However Points of Diversion is larger (~300,000 records). This is just too many points to send to the browser. The search api chokes on it as well for state-wide searches.

My proposal is to create a config for the search api to control the max number of records that it will successfully return. I'm think that we should try 50,000 to start with. It may need to be adjusted.

The search api should count the records as it is processing the results of a search. If it hits the max record count for a particular record, then it should short circuit the entire query/request and return an error message like this:
```json
"status": <something other than 200>,
"message": "Max record count exceeded for layer: 24"
```

This would help me implement the proposed solution to #283.

**Comment by steveoh** [comment]
What do you think about returning the partial result with the message. I would expect people to then limit their search somehow but it might be good enough to give them the subset instead of nothing. Thoughts?

**Comment by stdavis** [comment]
I think that a subset that's arbitrarily truncated would cause more problems and confusions than be helpful. I can't think of an instance were that would be helpful. But maybe I'm missing a use case.

**Comment by steveoh** [comment]
I don't mind either way, but since we are doing the work to get the records and the count it makes sense to return that and not waste it. We have the message that it was truncated to eliminate confusion.

**Comment by stdavis** [comment]
If you don't mind I'd like to not return the data. Just adds complexity and unnecessary bandwidth usage. I've spoken to Harold and Mike P about it and they are OK with it as well. Are you available to work on this this week?

**Comment by steveoh** [comment]
@brigsz what are your thoughts on schedules?

**Comment by brigsz** [comment]
Okay, let me look at the string, and then I need to remember what Steve is
up to.  How many hours do you think?  Under 20?

**Comment by steveoh** [comment]
Yes, the 4-10 range.

**Comment by brigsz** [comment]
Okay, I would say, pick your day.

**Comment by steveoh** [comment]
You got it.

**Comment by steveoh** [comment]
If you search for 5 layers and 1 has more than 50k records you want to fail the entire request? What about if the sum of all the layers is greater than 50k records?

**Comment by stdavis** [comment]
We have not done error messages specific to the layer for other things so yes, fail the entire search. I think that limit of 50k for a single layer is fine. No need to sum. 

-Scott

**Comment by stdavis** [comment]
4dc2cfca0365dc980e8507200343aa66759c03d9 was also related to this issue.
