### ISSUE TITLE
PLSS Labels

### ISSUE THREAD

**Issue by steveoh** [agrc/deq-enviro#313]
Cache levels 8-11 show a lot of plss labels for sections.

![image](https://cloud.githubusercontent.com/assets/325813/7171112/9a9c39ac-e391-11e4-9319-2922ee3d3efc.png)

Also, when you enable this layer and zoom out past where it's scale level is, it creates a lot of 404 requests.

![image](https://cloud.githubusercontent.com/assets/325813/7171134/d202abba-e391-11e4-8e6e-17b393187737.png)

**Comment by hsandbeck** [comment]
Hello Scott,

I was not able to replicate this issue that Steve found by getting the "404" error messages.  But, I suspect that it may be messages that you guys would see?  Anyway, just letting you know that there appear to be no hang-ups necessarily with the new live map.  Let me know if there is anything esle that I should test?  Will this be part of the 1.1 release?  Thanks for all your and Steve's help!!!!

**Comment by stdavis** [comment]
It's not an error that you would see unless you have your browser's
developer tools open. Not a big deal. Just a bit of clean up that's needed.
Users shouldn't see any errors.

On Thu, Apr 16, 2015 at 7:42 AM, hsandbeck <notifications@github.com> wrote:

> Hello Scott,
>
> I was not able to replicate this issue that Steve found by getting the
> "404" error messages. But, I suspect that it may be messages that you guys
> would see? Anyway, just letting you know that there appear to be no
> hang-ups necessarily with the new live map. Let me know if there is
> anything esle that I should test? Will this be part of the 1.1 release?
> Thanks for all your and Steve's help!!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/deq-enviro/issues/313#issuecomment-93736925>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by stdavis** [comment]
This was fixed with the release of the new PLSS cache. You should see the fix in production. No changes to this app were needed.
