### ISSUE TITLE
Search problem with DDW Public Water System Facilities

### ISSUE THREAD

**Issue by hsandbeck** [agrc/deq-enviro#320]
Harold,

I have narrowed it down to the Public Water System Facilities layer. When I perform a search and this layer is included, the map zooms to an area that roughly covers Mexico. The Zoom to Feature function zooms to the correct place.

I don't think it is a data problem. When I zoom to the geodatabase feature class that is the source of the data at AGRC, it zooms to the State.

However, as I am testing the production version (3:20 PM Tuesday) the map is having some other challenges, so maybe Scott is working on this right now.

Scott, I was able to confirm this bug on my desktop.....

**Comment by stdavis** [comment]
@hsandbeck: I'm unable to reproduce this bug. I'm guessing that it was a data issue but not sure. Can you see if you are able to verify?
