### ISSUE TITLE
Legend for Source Water Assessment Zones

### ISSUE THREAD

**Issue by hsandbeck** [agrc/deq-enviro#321]
![image](https://cloud.githubusercontent.com/assets/7117423/8318807/6af2fbea-19c5-11e5-925a-2c1d8515439e.png)
![image](https://cloud.githubusercontent.com/assets/7117423/8318816/79ff4dbe-19c5-11e5-8188-805778591b6d.png)

**Comment by stdavis** [comment]
@hsandbeck: This has been pushed to test for review.
