### ISSUE TITLE
v1.1.0 Push to Prod Steps

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#334]
- [x] Move PLSS vector tiles to the AGRC AGOL org and make it official
- [x] Run `reprojectDB.py` on the prod databases
- [x] Republish SOE
- [x] Republish Search.Api service
- [x] Verify new DB's and remove the old ones
- [x] Republish map services
- [x] Publish PrintProxy service
- [x] Copy column "Coded Values" from test config to production config
- [x] DEQ Config: Add "; Drinking Water" to points of diversion layer under "Division Heading" column
- [x] Update nightly script and test manually
- [x] Update the changelog and bump the version number
- [x] deploy web app
- [x] take a look at coordinate system of reference layers.
- [x] ask Harold/Marc about a fresh copy from deq config prod to test
- [x] update print-proxy deploy notes about secrets.py

**Comment by stdavis** [comment]
:fireworks: :raised_hands:

**Comment by steveoh** [comment]
:clap:
