### ISSUE TITLE
Deprecate http://mapserv.utah.gov/surfacewaterquality/ & wq.deq.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#355]
Once the DWQ enhancements (1.3) are pushed to production the current app at this address needs to be retired.

@hsandbeck: Do you want these URL's forwarded directly to enviro.deq.utah.gov?

**Comment by hsandbeck** [comment]
Hello Scott,

Let me get back to you this Monday regarding your question.

**Comment by brigsz** [comment]
Ha!  The responsible citizens of the Water Assessment community think this is heresy!

**Comment by hsandbeck** [comment]
Hello Scott,

I think that would be a good idea to have the old DWQ Beneficial Uses Interactive Map "URL's forwarded directly to enviro.deq.utah.gov".  I have talked to Mark Stanger and he is in agreement.

**Comment by stdavis** [comment]
Great. Thanks for the input.

**Comment by stdavis** [comment]
I finally got around to adding this redirect. This issue fell through the cracks.

wq.deq.utah.gov and mapserv.utah.gov/surfacewaterquality both now redirect to enviro.deq.utah.gov.

**Comment by stdavis** [comment]
![mail google com_mail_u_0__ui 2 ik f5d7772805 jsver c6entt0uzcq en view pt search inbox th 161f88183332a0e8 siml 161f73f02be138c5 siml 161f75dfb91afcad siml 161f76843f87425e siml 161f76ef6f4c125a siml 161f88183332a0e8](https://user-images.githubusercontent.com/1326248/37005979-5adb979e-2093-11e8-85a2-b6c296bc7ac6.png)

:(

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/42787025-d3139db6-8915-11e8-9e36-818edf8954bd.png)

**Comment by stdavis** [comment]
I don't believe that this is going to happen.
