### ISSUE TITLE
Forklift Pallet: Invalid null values in some tables that participate in relationship classes

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#372]
I'm seeing null values show up in some tables that participate as the destination table in relationship classes. The null values are in the field used as the foreign key in the relationship classes.

For example (DEQMAP_CERCLABRANCHACTMAJ):
![image](https://user-images.githubusercontent.com/1326248/30281050-9dee767c-96ce-11e7-8ae4-4765468f2197.png)

This table participates in the following relationship classes:
![image](https://user-images.githubusercontent.com/1326248/30288043-8fdb185e-96e4-11e7-8e2d-6e467201cf2d.png)

All of which use `ACLINK_KEY` as a foreign key.

I'm seeing the issue with data in `deqquerylayers.gdb` as well as the corresponding tables in SGID. However, the same table in `sgid_stage.gdb` does not have the problem.
![image](https://user-images.githubusercontent.com/1326248/30281212-0c648fba-96cf-11e7-88a4-ee4b2c6a8723.png)

Perhaps because `sgid_stage.gdb` does not have any relationship classes defined?

**Comment by steveoh** [comment]
That sounds like a doozy

**Comment by stdavis** [comment]
Here's the forklift log for posterity: [forklift.log.gz](https://github.com/agrc/deq-enviro/files/1293404/forklift.log.gz)

**Comment by stdavis** [comment]
And the forklift report: 
![image](https://user-images.githubusercontent.com/1326248/30287961-4d9b7b28-96e4-11e7-8e74-699f1039fb02.png)

**Comment by stdavis** [comment]
There was one row added to the source data for the problem table:
![image](https://user-images.githubusercontent.com/1326248/30298877-5158d30c-970a-11e7-91a2-599343b3044a.png)

**Comment by stdavis** [comment]
This morning I deleted all of the relationship classes that are involved with this data from SGID. I've got the code to quickly recreate them if needed. We'll see if that makes a difference for the next time this data is updated.

**Comment by stdavis** [comment]
I checked this data today and it seems OK. Close this for now.
