### ISSUE TITLE
Add actual max number of returned records to error message text

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#378]
From @nathankota:
>Would it be worth mentioning the max returned records value (25k) in the error message when a query exceeds it?

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/80261618-2aad7700-8648-11ea-9453-6335cec38f3a.png)

**Comment by nathankota** [comment]
Yes, I think it would be helpful to provide some context.
