### ISSUE TITLE
Reference layer removal - Indian Country and Tribal

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#384]
Please remove (or hide, as suggested by client) the _Indian Country and Tribal_ data layer from the Map Reference Layers. Whichever is easiest and less time-consuming (remove vs. hide).

**Comment by steveoh** [comment]
Was this meant for the DAQ app?

**Comment by nathankota** [comment]
They're concerned about it on the enviro app, which is public-facing. It can stay on the DAQ app.

**Comment by stdavis** [comment]
I've just pushed `v1.5.0` that hides this layer. This is just a quick-and-dirty hiding of the control. To completely remove this layer from the project I still need to:
- [ ] remove the layer from `maps/MapService.mxd`
- [ ] update the layer indexes [in config.js](https://github.com/agrc/deq-enviro/blob/8c4c569240c7cea49f666ca5815af4ddc2b41ccd/_src/app/config.js#L178-L189)
