### ISSUE TITLE
Remove Environmental Risk layers

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#395]
From Rick Saathoff:

> ...please remove the Environmental Risk Lakes, Environmental Risk Streams, Environmental Risk Water Points, and Environmental Risk of UST Facilities...

from the reference layers of the enviro interactive map.

![image](https://user-images.githubusercontent.com/15659642/83437002-36851980-a3fc-11ea-80fd-a2aa0149157f.png)

**Comment by stdavis** [comment]
This has been pushed to production as v1.6.4.

@nathankota Would you mind letting the client know? It sounds like he reached out to you directly.
