### ISSUE TITLE
Move static data from deqquerylayers.gdb to a separate gdb

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#397]
DAQAirOilGasEmissionsPt & DAQAirOilGasEmissions are static datasets that have no source. They should be moved to a separate FGDB so that deqquerylayers.gdb can be deleted and recreated without having to manually copy data.

**Comment by stdavis** [comment]
Emailed Michelle about these layers. I wonder if they can just be removed from the app.

**Comment by nathankota** [comment]
![image](https://user-images.githubusercontent.com/15659642/86281938-8aba1f80-bb9b-11ea-9872-f41e38df19d2.png)
