### ISSUE TITLE
Add parcels as reference layer

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#398]
- Use either [vector tile layer](https://utah.maps.arcgis.com/home/item.html?id=71d0a7ba7c6745fc88de84e7d9e5f066) or [feature layer](https://utah.maps.arcgis.com/home/item.html?id=9df536b0835e4ee78e34d7cf6fe132c2) 
- Include parcel number as label
- Explore scale dependency for better responsiveness

![image](https://user-images.githubusercontent.com/15659642/84445871-88e6e700-ac01-11ea-9584-03ad440fe766.png)

**Comment by nathankota** [comment]
Approval by DEQ (Deidre) to push to production:

> I like this. This works and will be very helpful for many of our stakeholders. Let me know when it has been added to the real site.

**Comment by stdavis** [comment]
v1.7.0 (including this feature) has been pushed to production.
