### ISSUE TITLE
Migrate or Remove Nancy API & Associated SOE

### ISSUE THREAD

**Issue by steveoh** [agrc/deq-enviro#412]
The API provides:
* simplified queries on the client-side
* location- and temporal-based authorization

We could update the client-side code to make separate queries to the individual feature services for each query layer.

I hope that authentication will be gone at some point.

We need to decide if we want to migrate the API to a GCP function or if we can get rid of it altogether.

https://github.com/NancyFx/Nancy is no longer maintained and should be migrated to the latest microsoft .net 5 web api framework and hosted as a GCP function.

**Comment by stdavis** [comment]
The plan for v2 is to deprecate the API/SOE in favor of client-side queries directly to feature services.

**Comment by stdavis** [comment]
I feel good about the current solution for the new app. FeatureLayer queries plus the create replica AGOL endpoint for downloads.
