### ISSUE TITLE
Add Drinking Water System Ratings Query Layer

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#419]
From Rachel:
>In my followup meeting with DDW they decided that they only want to symbolize water system ratings in the enviro map, and currently do not want to show any related data. I have created a view in the UTAHDDW AT Database called VW_DDW_SYSTEM_RATINGS.
 
>I'm thinking that this could be joined to the culinary water feature class where our pwsid field is equal to the feature layers DWSYSNUM field. Once joined, the layer could be symbolized based on the 'rating' field. 

>The colors DDW is familiar with seeing for this are:

>Approved: #108c4f 
>Non-Approved: #a40606
>Corrective Action: #d2b307

>Would it also be possible to filter by the 'status' field (Active or Inactive) as well as 'systemtype' field? (yes)

>DDW Would like to show all the fields provided in the view except the systemid field (first column) in the view if possible. I have ordered the columns in order of importance.

**Comment by stdavis** [comment]
Keep the `COUNTY` field from the feature layer.

**Comment by stdavis** [comment]
@nathankota I think that I have this up and running on https://test.mapserv.utah.gov/deqenviro/. Want to give it a look and then send it to the client for feedback?

**Comment by nathankota** [comment]
It all seems to function as expected but I noticed something odd about their related culinary drinking water boundaries.

WHERE
**Filter:** `Status = Inactive`
**Search Criteria:** `City = Salt Lake City`

Although all of the returned features were spatially within Salt Lake City, only one of them was actually in SLCO according to the Water Link pages. The returned results and associated links were:

- [Red Cliff Warm Spring](https://waterlink.utah.gov/deqWater/reports.html?systemId=1226)
- [Buehner Block Company](https://waterlink.utah.gov/deqWater/reports.html?systemId=204) (in SLCO)
- [Burns RV Park](https://waterlink.utah.gov/deqWater/reports.html?systemId=206)
- [Burrville Culinary Water](https://waterlink.utah.gov/deqWater/reports.html?systemId=207)
- [Red Cliffs](https://waterlink.utah.gov/deqWater/reports.html?systemId=1227)
- [Sugarhouse Rec Property](https://waterlink.utah.gov/deqWater/reports.html?systemId=1450)
- [Phoston Terminal](https://waterlink.utah.gov/deqWater/reports.html?systemId=1155)
- [Long Rider Cafe and Trailer Court
](https://waterlink.utah.gov/deqWater/reports.html?systemId=444)

**Comment by stdavis** [comment]
The city is just a spatial intersect with the municipal boundaries. Could BBC be touching the boundary?
