### ISSUE TITLE
Environmental Covenants Reference Layer

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#432]
We discovered today that this layer is not being updated. The current pallet for this app pulls from SGID (internal) but nothing updates SGID. I believe that this happened back when this layer was moved from being a query layer to a reference layer a few years ago.

Michelle is working on getting a permanent home for the source data. Then a pallet will need to be wired up to it to update the SGID data. Or maybe we can just pull this out of SGID and update the app database directly from the source?

@nathankota suggested that DEQ move this data to AGOL as a test to see how that goes.

**Comment by stdavis** [comment]
@nathankota Have you heard about any movement on this dataset? Did they decide to push it to AGOL?

**Comment by nathankota** [comment]
It is still pending. I chatted with R.S. about it for a while yesterday, and ultimately offered some assistance to make it happen. We're close to having a decision.

**Comment by nathankota** [comment]
They plan to create an AGOL layer. Checked in this morning to see if/how we can help push it forward.

**Comment by nathankota** [comment]
https://utahdeq.maps.arcgis.com/home/item.html?id=24c7e34093d24563ba360fa46f67317b

**Comment by stdavis** [comment]
@nathankota It looks like she didn't match the symbology from the current layer. I don't know if that's important to her or not. Here's a layer file with the symbology from the old layer if she wants it:
[Environmental Covenants.lyr.zip](https://github.com/agrc/deq-enviro/files/8292831/Environmental.Covenants.lyr.zip)

**Comment by stdavis** [comment]
This has been pushed to https://test.mapserv.utah.gov/deqenviro/. Any default symbology changes to the source AGOL item should immediately be reflected in the app.

**Comment by nathankota** [comment]
The default symbology has been changed. Will validate with DEQ.

**Comment by stdavis** [comment]
I can see the new symbology in the app now. Do they want a legend shown?
<img width="367" alt="image" src="https://user-images.githubusercontent.com/1326248/159057006-35ce79a8-424e-4c0b-856a-aa85ac09292e.png">

**Comment by stdavis** [comment]
I'm pushing a new build to test (v1.8.5-2) that includes the legend for this layer. It should be done in about 10 minutes.
