### ISSUE TITLE
Change "Select Query Layers" text

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#434]
From: `Select Query Layers`
To: `Select Layers`

![image](https://user-images.githubusercontent.com/15659642/157125630-d0d89110-6cc3-4f27-af9d-fd97891f81cc.png)

**Comment by steveoh** [comment]
In my opinion `Query Layer` and  `Layer` are very developer/GIS terms. I wonder if there is a more relatable term for this heading.

**Comment by nathankota** [comment]
> In my opinion `Query Layer` and `Layer` are very developer/GIS terms. I wonder if there is a more relatable term for this heading.

`Map Data` or `Map Layer` ?

**Comment by steveoh** [comment]
Personally data seems like an improvement.

**Comment by nathankota** [comment]
presented `Select Map Data` to client, and waiting for their confirmation

**Comment by nathankota** [comment]
Client accepted `Select Map Data`
