### ISSUE TITLE
Water Quality - Assessed Waters 2022 filter not showing polygons

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#446]
- Under _Select Map Data_ , click on  _Water Quality_  
- Select _Assessed Waters 2022_ 
- Click filter button and select _5: TMDL Required (303d List) / 4A: TMDL Approved (Impaired)_ 
- Click _Apply Filter_ 
- Scroll down to Advanced Search 
- Select _Statewide/County_ and _Statewide_ 
- Click _Search_

## Observed
- Proper number of records (77) are populated in the table below the map
- Boundaries do not load on the map

## Expected
- Records populate table below map
- Assessed water boundaries for the selected layer are shown on the map

Notes from Mark S.

> The data layer Assessed_Water_2022 properly selects the assessment unit polygons where ASSESSMENT = 5: TMDL Required (Impaired 303d list) and 4A: TMDL Approved  but a collegue here at DWQ noticed they are missing on screen. I suspect it is because the legend does not match. The filter also works properly when filtering for the combined 5 and 4A assessments. They are also highlighted in pink when the cursor hovers over the record in the table (grid). The 2020 assessment wording changed, slightly from:

> 5: TMDL Required (303d List) / 4A: TMDL Approved (Impaired)                             (2020 assessment category)
> 
> and was revised to: 
> 
> 5: TMDL Required (Impaired 303d list) and 4A: TMDL Approved (Impaired)          (2022 assessment category)
> 
> I will attach the new layer file.

**Comment by steveoh** [comment]
I've been looking at this all morning. The data is different than the map service symbology expects. The layer file provided from DEQ is not correct. I manually updated it from the data we have and published to the test server but that did not give the desired results. I do not want to make the situation worse for the UGIC presentation so I will assign this to scott for when he's back to working with time. 

In the future, if the data that is driving symbology is planning to change, we should communicate those changes prior to important events so they can be addressed properly.
