### ISSUE TITLE
Upgrade Google Analytics to 4

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#475]
Terry Davis is concerned about losing legacy data if we don't upgrade before July 1st.

**Comment by nathankota** [comment]
Should we put a reminder on this?

**Comment by stdavis** [comment]
Sure. I added the reminder action.

**Comment by stdavis** [comment]
/remind me to implement this on June 15th

**Comment by nathankota** [comment]
<html>
<body>


We’ll soon configure Google Analytics 4 for you
--
Hello.Universal Analytics standard properties will stop processing data on July 1, 2023. To maximize historical data and to ensure that Google Analytics 4 (GA4) meets your specific needs, we recommend you make the switch to Google Analytics 4 now. This will give you the opportunity to customize the setup including using the latest site tag.
For any customer who does not set up a GA4 property with basic settings, starting in March, we will configure one with a few basic settings consistent with the existing Universal Analytics property; this includes certain conversion events, Google Ads links, and existing website tags.For Universal Analytics customers whose websites are tagged with gtag.js or analytics.js (including through tag management systems like Google Tag Manager), we will create a connected site tag that will reuse existing tags when possible to send traffic to the new GA4 property. If you do not wish to have a GA4 property created and configured based on your Universal Analytics property and existing tags, you may opt-out.


</body>
</html>We’ll soon configure Google Analytics 4 for you

Hello.

Universal Analytics standard properties will stop processing data on July 1, 2023. To maximize historical data and to ensure that Google Analytics 4 (GA4) meets your specific needs, [we recommend you make the switch to Google Analytics 4 now](https://notifications.google.com/g/p/APdRdFzDr15Vz89k2u7M-EfQJLuqz84MD9OpAgOI1Z52qEOzHCWIFrpdmgABbaAdWgZ1ekx8SE_jehZ6_KRrW30jhxDbhl92UT8BH96iY0o2LimWgs-8Sg62zFcLXQAuy7scZckNKX-Ul5KyZMFMcsBirC90zoFcuot-uxQKKKZchdz_wHcrLFkgsG1W9PESBCs9-YORGg7Nt0qpoGYekOIEWLDjbYghNzvbgOKB80V4l3NkuUxX4oD6s0PnndW3v1XV4_JoPRdflsUj3apkwEMNkNu9jRdvCOCHwvZ8ar-ATukvAGdwdIJOWLYFCcto-nAP6JtQYcP_gqua1PSBMXb_pFHs). This will give you the opportunity to customize the setup including using the latest site tag.

For any customer who does not set up a GA4 property with basic settings, starting in March, we will configure one with a few basic settings consistent with the existing Universal Analytics property; this includes certain conversion events, Google Ads links, and existing website tags.

For Universal Analytics customers whose websites are tagged with gtag.js or analytics.js (including through tag management systems like Google Tag Manager), we will create a connected site tag that will reuse existing tags when possible to send traffic to the new GA4 property. If you do not wish to have a GA4 property created and configured based on your Universal Analytics property and existing tags, [you may opt-out](https://notifications.google.com/g/p/APdRdFz98casb-JL5-I1fsxbM71bFM_t6WUbF2QSE3NhmMJMUYUhWvwYPAO38iE6OwPxw7xdTAORiiCDRwBiO8hutsvASwrnJlHNbugRtwJkzDfIwpa9QjZZBlF6o-gB7eejXdHH_HG4Mg5-KYFUZ9F-65XgM8W0HeZKxDNdtPqJm_YU58HvTjv7DgcS-uzEswHOJ6nTgCyqFAM6qHNdE7mprCfIInuzX0Eh8LudtD7Eok8bAiEbLX3pqnOeAv_QN2hn4bUGBkteENy2ENlsrFxFcw680EainP6cCS9mpIvD3WWE3H629EbiFyU).

[Learn more](https://notifications.google.com/g/p/APdRdFw9Pt7lg3yZqIX1LJtu11lVcQCu_RUK79zjq9vkLD7bvGbExnU7q7zPfyvhcN3AdnhELhbFap2zp14OS-1ihs0C2mCC53mkDuN4yAyiGncI78RVHaYL1c1Z6zKXmE5Mb4J-SFwO88cWmG358hDw81SQa-Lt45rZeDcv_WhDYtQZssQj0_zs2S9tlO4O_YuhuN0ak8CvSt-2s-GNQOjJcqbU5NAKwVDoALAZhpht1_SDiqW_0vdOXGGbXinWNyodbctFnF30FMwRT8z1X6kqHVcEi3SSdylVCjpPAmtonz76SqUH-g)
Sincerely,

The Google Analytics Team

**Comment by stdavis** [comment]
Done
