### ISSUE TITLE
Add clarifying verbiage to sign in/request access component

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#485]
From Deidre:

> People are requesting access even though they don't really want access to the Public Water System Facilities. They think because of the "Sign In" link at the top of the map that they have to sign in to access all data. This has happened multiple times in the recent past.
> 
> Would it be possible to add a sentence in the pop-up box that appears when requesting access under "Sign In or Request Access", that says something like this:
> 
> A request for access is only necessary to view Public Water System Facilities. If you do not need to view this layer, please do not request access.

![image](https://user-images.githubusercontent.com/15659642/209353503-3ea207da-4182-42c7-ba92-efdd52b9253a.png)

**Comment by stdavis** [comment]
This is no longer valid since there will be no secure layers in the next version of this app.
