### ISSUE TITLE
Related records not working

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#489]
From Rick S:

> ...the related records on the interactive map aren't showing up. Look at 0100030 for an example. The views on my end have the data.

**Comment by stdavis** [comment]
I fixed this by deleting the FGDBs in hashing and letting forklift recreate them from scratch. The issue was that the `queryRelatedRecords` endpoint was returning records from an incorrect layer. It was very strange since all of the layer ids from the service seemed to line up to me.
