### ISSUE TITLE
Remove Hourly Air Monitoring Update

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#493]
[This script](https://github.com/agrc/deq-enviro/issues/84) is still running, and we would like to know if it is still needed; if any changes or updates need to happen based on the new architecture that will arise from the enviro tech debt project; or if it can/should be deprecated.

**Comment by nathankota** [comment]
/remind me to ask Lexie about this in two weeks

**Comment by stdavis** [comment]
@nathankota Did Lexie ever get back to you about this?

**Comment by nathankota** [comment]
No. Just dinged her again.

**Comment by nathankota** [comment]
/remind me to ding Lexie again in one week
