### ISSUE TITLE
Wire up Config Spreadsheet to Firebase Remote Config

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#494]
- [x] Create a function that reads the config spreadsheet and updates Firebase remote config
- [x] Figure out if there's a way to automatically kick off the function when changes are made to the config spreadsheet
- [x] Integrate remote config into the front end app

**Comment by stdavis** [comment]
I ended up adding a custom menu with a button for pushing the configs to the app. I felt like that this was a safer solution than an onEdit trigger.



![Image](https://user-images.githubusercontent.com/1326248/233498761-71b68120-e209-48ad-bf6b-0c6d7e6f7b52.png)



![Image](https://user-images.githubusercontent.com/1326248/233499089-9c0b9780-4e99-472e-9010-f1c50743a6ad.png)

**Comment by steveoh** [comment]
Who has permission to click that button?

**Comment by nathankota** [comment]
I went through a few steps to allow the function to access my google account and such, and ultimately ended up with
![image](https://user-images.githubusercontent.com/15659642/233667681-53a4d4b8-fd8c-4ab8-a486-c583a5b0ebcc.png)

**Comment by stdavis** [comment]
Hmm. Interesting. You didn't have any issues with the onEdit trigger but you can't click the button. Not sure on that one. I'll see what I can come up with...

**Comment by stdavis** [comment]
@nathankota Can you remind me; we got this solved, correct? You are able to click the "Deploy Staging..." menu item successfully?

**Comment by nathankota** [comment]
I thought is worked when I last tested, but just now I got
![image](https://user-images.githubusercontent.com/15659642/236343996-44ff7d3e-6cf9-402c-b0ee-8a2eff7ecbd6.png)

It looks like enviro.dev.utah.gov changed once despite the error, but didn't change back when I edited the sheet and got the same deploy error

**Comment by stdavis** [comment]
At least the permissions are working now. :) Let's try this again after the next dev release. I've messed with the sheet and update function locally a lot since the last one.

**Comment by nathankota** [comment]
> At least the permissions are working now. :) Let's try this again after the next dev release. I've messed with the sheet and update function locally a lot since the last one.

ok, I'll test again when ready

**Comment by stdavis** [comment]
OK, @nathankota. I've pushed a new deploy. Give this another try when you get a minute.

**Comment by nathankota** [comment]
eureka!
- opened enviro.dev.utah.gov and expanded the Drinking Water layer selector
- changed the first layer name on the [test config sheet](https://docs.google.com/spreadsheets/d/1aVJ68hOyp4H6sKEEuL-xtB2qE_y6W0gDg35TgUSxtFg/edit#gid=0)
- ran the deploy to configs script on the sheet
![image](https://user-images.githubusercontent.com/15659642/236871616-c7cf61ec-bb2a-4ac7-87cc-2e907085256d.png)

- refreshed the dev app and the changes were present
![image](https://user-images.githubusercontent.com/15659642/236871564-51accd79-490b-49f3-9717-1c1d40538463.png)
- changed layer name back to expected, ran script again, refreshed dev app, and changes were applied
- went back to config sheet and ran deploy script again without and sheet changes
![image](https://user-images.githubusercontent.com/15659642/236872519-dce3da5d-4420-4cbf-b569-261e92628036.png)
