### ISSUE TITLE
Add Feature Count Limit

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#536]
Points of Diversion crashed the page.

**Comment by stdavis** [comment]
Added limit of 50,000

**Comment by nathankota** [comment]
Searched DERR > Water Rights Points of Diversion > Statewide

The first time it crashed the page, but I didn't take a screenshot of the error. However, there was a button to `Reload`, which refreshed the page and the same query resulted in the proper message about exceeding the max number of allowable records and to narrow the search. I replicated the points of diversion statewide query several more times on a couple browsers and the results were as expected. I think this can be considered validated.
