### ISSUE TITLE
Advanced Searches

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#537]
- [x] county
- [x] city
- [x] zip
- [x] street address
- [x] name (not sure how to implement this)
- [x] id (ditto)
- [x] shape
- [x] nhd stream name
- [x] coordinates

**Comment by nathankota** [comment]
## County Test
### Search Parameters
DDW: GWPZ
DAQ: Oil & Gas Wells and Air Monitoring by Station
DERR: Water Rights POD
Advanced: Juab

### Current app results
![image](https://github.com/agrc/deq-enviro/assets/15659642/165030a1-20ea-4ab3-9f28-a855fc1187c5)

### Dev app results
![image](https://github.com/agrc/deq-enviro/assets/15659642/418fbc1a-24ac-4d1b-b8a2-8f1d83e39d4b)

**Comment by stdavis** [comment]
# Research

## Points of Diversion
**Search: Juab County**
New App: `5454`
Old App: `3603`

OpenSGID: `5457`

**Comment by nathankota** [comment]
I've done some additional testing and I'm ready to close this down as it is, and we can accumulate feedback from the DEQ testing team for any new issues.
