### ISSUE TITLE
Use new EPA data from DEQ's AGOL

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#542]
1. [Ozone Nonattainment/Maintenance Areas](https://services2.arcgis.com/NnxP4LZ3zX8wWmP9/arcgis/rest/services/Ozone8hr2015_UTAH/FeatureServer)
 
2. [PM 2.5 Nonattainment/Maintenance Areas](https://services2.arcgis.com/NnxP4LZ3zX8wWmP9/arcgis/rest/services/PM2_5_24hr2006_UTAH/FeatureServer)

**Comment by stdavis** [comment]
I've got these updated in the test config spreadsheet. Thanks!
