### ISSUE TITLE
Map Labels

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#550]
These should probably be controlled via AGOL as well.

**Comment by stdavis** [comment]
We got this for free when I switched to using `fromPortalItem` for layers that support it.

**Comment by nathankota** [comment]
Validating based on testing of [Public Water System Ratings](https://utahdeq.maps.arcgis.com/apps/mapviewer/index.html?layers=56b14b5c604041bba7acad249e2b4fbc). There may be other layers with labels that we're not aware of.
