### ISSUE TITLE
Make results grid resizable

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#551]
~https://github.com/dorbus/flexboard~

These are looking like better possibilities:

https://github.com/bvaughn/react-resizable-panels

https://www.npmjs.com/package/react-draggable

Related to #552

**Comment by nathankota** [comment]
This is a great feature! I'm seeing some inconsistencies with where it appears. Below are the results of the same query on different sized browser windows. Can the draggable component be permanently aligned with the top of the results grid?

![image](https://github.com/agrc/deq-enviro/assets/15659642/0e49b856-0a81-4962-82f9-32c024baad7b)

![image](https://github.com/agrc/deq-enviro/assets/15659642/60ff6c66-d662-4ed5-ad1f-b50fd1ac6789)

**Comment by nathankota** [comment]
looks good 👍
