### ISSUE TITLE
Result Grid Default Height

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#552]
It is somewhat larger than the old version. Make the default height smaller or even a percentage of the screen height.

![Small_Map_Area](https://github.com/agrc/deq-enviro/assets/1326248/84bfc211-4547-4583-aefb-c33f045dbe8d)
![Map_Area_Prod](https://github.com/agrc/deq-enviro/assets/1326248/c5424fe3-5739-4746-a8a9-300b45d97a9d)

Also, [making the grid resizable will help](https://github.com/agrc/deq-enviro/issues/551).

**Comment by nathankota** [comment]
I think this is achieved with some tuning of #551
