### ISSUE TITLE
Advanced Filter not Reset on Start New Search

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#553]
## Reproduction
1. Make a search using advanced filter.
2. Click on "Start New Search"
3. Go back to advanced filter and notice that it has not been cleared even though the statewide graphic is shown on the map.

**Comment by nathankota** [comment]
I've done a bunch of statewide and advanced searches and this is working again. I did notice that I'm getting the error page randomly when starting a new search. Closing this one, and will create a new issue for the error page.
