### ISSUE TITLE
Layer-specific filters

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#555]
![Image](https://github.com/agrc/deq-enviro/assets/1326248/41978f32-8554-4fbd-ab10-a7ce9570570e)

**Comment by nathankota** [comment]
Tested and compared results between dev and prod apps for:
- Oil and Gas Wells > New Application for Permit to Drill (APD) - same results 
- Groundwater Protection Zones > Zone 1 - same results
- Environmental Incidents > between 2/4/2023-2/8/2024 - three less results in the dev app, but it worked well
- Petroleum Storage Tanks > Has UST(s) resulted in the following error:
 
![image](https://github.com/agrc/deq-enviro/assets/15659642/93abbde9-5f76-4d74-be5a-a6c5c422ed01)

**Comment by stdavis** [comment]
@nathankota I pushed a fix for the PST layer query bug. Thanks for catching that!

**Comment by nathankota** [comment]
thanks! looks good!
