### ISSUE TITLE
Rename oil and gas wells download file name

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#562]
Other layers' download files that I tested seemed good, and included the layer name as the file name. Oil and gas wells layer downloads all looked like:

![image](https://github.com/agrc/deq-enviro/assets/15659642/0d3f5677-23c4-476e-a58c-caf18d2adbcb)

**Comment by stdavis** [comment]
I'm not sure that we have any control over the file name since this is coming from an AGOL service. I'll look into it...

**Comment by stdavis** [comment]
This is solved with the new download service. Now the download file names match the "Table Name" column in the config spreadsheet.
