### ISSUE TITLE
Related Records

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#563]
There are [36 relationships](https://docs.google.com/spreadsheets/d/1aVJ68hOyp4H6sKEEuL-xtB2qE_y6W0gDg35TgUSxtFg/edit#gid=24097061) involved with this app. The current app houses all of the data in a single geodatabase and creates all appropriate relationship classes within it.

In the new AGOL-based architecture, the data is spread out into separate services. We need to decide between trying to combine related tables in the same service so native relationships can be used, or using the config spreadsheet to define relationships between tables in separate services.

Consider downloaded data when making this decision. In the current app, the user gets all of the data in a single FGDB with the appropriate relationship classes. This may be a reason to try keeping related data within the same service.

- [x] additional info field
- [x] downloads

**Comment by nathankota** [comment]
Validation (active) notes:
- I like how it only downloads the related table(s) that contain data.
- Tested and validated all download types for DERR > Brownfields Other
