### ISSUE TITLE
Don't show search geometry overlay for statewide searches

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#564]
Based on feedback from a user that did not use the advanced filter. It just gets in the way.

**Comment by stdavis** [comment]
I wonder if this is no longer an issue since I made the border more heavy and removed the cross-hatching? @nathankota Thoughts?



![Image](https://github.com/agrc/deq-enviro/assets/1326248/3907a5e8-09d8-4d42-9b42-2f80f32231b2)

**Comment by nathankota** [comment]
I like this solution, and how the advanced search areas also use the hashed boundary.
