### ISSUE TITLE
Top result table has secondary scrolling when scrolling to the bottom of the table

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#570]
To reproduce, do a statewide search on Air Monitoring by Station (no other layers) and scroll to the bottom of the results table. It continues to scroll into whitespace after the bottom of the table.

![Image](https://github.com/agrc/deq-enviro/assets/1326248/61566155-fd16-49a4-bbe8-0a29c0367955)

**Comment by nathankota** [comment]
validated
