### ISSUE TITLE
Custom Attribute Searches

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#572]
If you select only the wells dataset, these extra searches show up in the advanced filter list.

![Image](https://github.com/agrc/deq-enviro/assets/1326248/5ac9d111-eeab-4df2-9724-a09f23b8c3eb)

**Comment by stdavis** [comment]
I think that this may be related to this issue so keeping it open is great.

**Comment by stdavis** [comment]
@nathankota I just deployed a fix for this in v2.0.0-68. Thanks for the bug report!

**Comment by nathankota** [comment]
validated 👍
