### ISSUE TITLE
Add default opacity for point layers

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#574]
![Image](https://github.com/agrc/deq-enviro/assets/1326248/9ffd90c1-ccd1-4bd6-a553-e7bfd3c4f256)

vs

![Image](https://github.com/agrc/deq-enviro/assets/1326248/84bc3207-43e1-4e76-94fc-76552f6fb6d6)

**Comment by nathankota** [comment]
tested and validated on multiple point layer searches
