### ISSUE TITLE
How to support aliases in layers with non-geodatabase sources

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#577]
The real question is: Does forklift overwrite changes made to fields in the item details such as the alias value.

**Comment by stdavis** [comment]
Today I set the alias of `DERRID` to `DERR ID` for the [Environmental Incidents AGOL item](https://utah.maps.arcgis.com/home/item.html?id=892f7efacb8b4643b8e111a33d34a7f0).

/remind me to check to see if it has been overwritten in 5 days

**Comment by stdavis** [comment]
The change I made to the alias was overwritten last night. :( I think that I'll need to bring back the alias configuration via the config spreadsheet.

**Comment by stdavis** [comment]
This is working with the identify panel. It just needs to be implemented for the results grid tables.

**Comment by stdavis** [comment]
"Result Grid Fields" also now supports defining aliases.

**Comment by nathankota** [comment]
validated
