### ISSUE TITLE
Add Progress to Download Request

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#599]
Currently, the generate download zip request is a synchronous request that can take multiple minutes during which the user just sees a spinner with no indication of progress. An enhancement would be to [send the request and return with a job id](https://restfulapi.net/rest-api-design-for-long-running-tasks/) which the client could poll the server for updates. Then the app could display some sort of progress indicator as layers were processed.

It appears that [Celery](https://docs.celeryq.dev/en/stable/getting-started/introduction.html) is a standard way to do this. It would require a Redis instance. I did find some [simpler options](https://github.com/dchevell/flask-executor) but I don't know that they would work in a multiple-instance environment. 

I'm not sure that this is worth the effort for the initial push to prod but something to consider in the future.

**Comment by steveoh** [comment]
Redis is quite expensive as far as gcp services go. I wonder if it's worth the cost for this feature. 

Another alternative could be firebase's real time listeners. You can connect to a document and updates to it's values are streamed to the client. Maybe the download function could write to a firebase document as it processes through the request and stream the updates?

**Comment by stdavis** [comment]
I have no auth with this app so would that work with firebase?

**Comment by steveoh** [comment]
You would control the access rules and anonymous is available.

**Comment by stdavis** [comment]
@steveoh Using firestore to push status updates to the client was a great idea. I've got it working. Thanks for the tip!


![Image](https://github.com/agrc/deq-enviro/assets/1326248/158bffb5-1086-49de-bb3a-af6b38f55f6e)



![Image](https://github.com/agrc/deq-enviro/assets/1326248/8036ac8f-eba5-480e-96b2-cf6923c78bec)

**Comment by steveoh** [comment]
That is awesome scott!

**Comment by nathankota** [comment]
Agreed! This is awesome, and works great 👍
