### ISSUE TITLE
Add spinner to map to indicate drawing

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#633]
On larger searches, the results pan will open up and show the data, but the map does not show the geometries for a while. This can be confusing to users. Adding a spinner to the map to indicate that it is loading/drawing features would help.

**Comment by nathankota** [comment]
#### Test Query
**Layer:** Water Rights Points of Diversion
**Advanced:** Tooele County

#### Results
- The results pane loaded before the map data and I saw the spinner in the bottom right corner of the map, indicating that the points were still loading. It was a little hard to notice, but I am validating that this works as expected.
