### ISSUE TITLE
Allow Shape Definition to be Defined by Previously Selected Polygon

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#647]
Do a search on a polygon, then select a polygon, then change the advanced filter to shape and do another search based on the selected polygon.

**Comment by stdavis** [comment]
I added a button to the identify pane for this feature to make it more visible to users:


![Image](https://github.com/agrc/deq-enviro/assets/1326248/ce83a16e-aed8-4d8e-b737-ac0150b01d51)

I'm open to suggestions for a better name for the button.

**Comment by nathankota** [comment]
Validating based on the funcationality of the search feature, despite the tester's comments that there was an error when initially searching the tested polygon feature (groundwater protection zones).

> Something Went Wrong "Cannot read properties of undefined (reading 'Layer Name')
