### ISSUE TITLE
CERCLA - NPL layer Project Description attribute - html in text

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#656]
Layer: DERR, CERCLA National Priorities List
Example for the following record
![image](https://github.com/agrc/deq-enviro/assets/15659642/0b748bcf-a4fa-4510-bf73-141f509db337)

Current production app:
![image](https://github.com/agrc/deq-enviro/assets/15659642/ac777709-9b40-4615-9b64-e84aac86e0c8)

New/dev app:
![image](https://github.com/agrc/deq-enviro/assets/15659642/ec96a5de-8f9d-45ee-a1f7-197fd745fe49)

**Comment by stdavis** [comment]
This has been pushed to `v2.0.0-73`.

**Comment by nathankota** [comment]
checked all 26 CERCLA NPL records and they look good...validated
