### ISSUE TITLE
Errors on first search, resolved on reload and repeat of search

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#658]
I'm seeing a lot of these errors the first time I do a search, then I click reload and run the search again and it works. The error is always the same. I don't think it's specific to polygon layers, or that's just where I've noticed it the most, such as, 

Environmental Justice > EJ Demographic Index
Air Quality > Ozone Nonattainment...
Air Quality > PM 2.5 Nonattainment...
Drinking Water > Ground Water Protection Zones

`Something Went Wrong "Cannot read properties of undefined (reading 'Layer Name')`

   `at Msn (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:4985:86586)`
    `at pte (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:38:19716)`
    `at zH (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:3159)`
    `at $Te (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:2369)`
    `at Ide (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:1909)`
    `at KTe (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:47621)`
    `at HTe (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:40005)`
    `at lXe (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:39928)`
    `at cL (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:39776)`
    `at XH (https://enviro.dev.utah.gov/assets/index-qd5vdsFZ.js:40:36109)`

**Comment by stdavis** [comment]
I'm struggling to reproduce this. Is this happening after you click search after a fresh reload of the site or after you click "Start New Search"? If you can get it to happen again, would you mind opening up the developer tools console and posting the contents of it to this issue? I pushed a new release today that adds some logging to help diagnose the issue.

**Comment by nathankota** [comment]
Thanks for looking into it. I queried a bunch of poly layers, let the app sit open and unused for an hour or more, then did a bunch more queries and everything worked well and the results were snappy. I'm going to close this and move on.
