### ISSUE TITLE
Use new database/source for Air Quality > Point Source Emissions layer

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#662]
The TEMPO database has been replaced by SLEIS (pronounced "slice") for point source emissions facilities and data. Below are the attributes currently included in the Point Source Emissions data set from TEMPO that we would like to get from SLEIS via a database view. Shawn Neville is the SLEIS DBA, and was contacted on 3/18/2024 about setting up a read-only view to connect to.

```
DAQ_ID (DAQ ID)
COMPANY (Site Name)
ADDRESS1 (Site Address)
ADDRESS2 (Address)
ADDRESS3 (Address)
CITY (Site City)
COUNTY (Site County)
EASTING (UTM_Easting)
NORTHING (UTM_Northing)
YEAR (Year)
CARBON_MONOXIDE (Carbon Monoxide (TONS/YR))
OXIDES_NITROGEN (Oxides of Nitrogen (TONS/YR))
AMMONIA (Ammonia (TONS/YR))
PARTICULATE_MATTER_PM10 (Particulate Matter - PM10 (TONS/YR))
OXIDES_SULFUR (Oxides of Sulfur (TONS/YR))
PM25 (Particulate Matter - PM2.5 (TONS/YR))
VOLATILE_ORGANIC_COMPOUNDS (Volatile Organic Compounds (TONS/YR))
```

**Comment by nathankota** [comment]
Shawn Neville:

> The SLEIS database is managed by the shared database team. I've submitted ticket INC1970033 to request that a read-only user be created on the SLEIS database.
I don't have an understanding of the data stored in the SLEIS tables yet. Once the new user is created, I think it would be best to first coordinate with SLEIS staff users to see if they can help find the tables/columns that correspond with Tempo data. 

Scott:

> Jeff Howard got me login credentials to the DEQSLEISPROD database and I was able to successfully connect. The next step is to build a view of the specific fields needed for the interactive map.

Shawn:

> Catherine,
Are you familiar with the SLEIS SQL tables (details about data the tables hold)? If not, would Bret be our point of contact to get a meeting set up to help us find the needed data in SLEIS?

Catherine Williams:

> We do not have backend access anymore to SLEIS, so I think we should definitely talk to Bret and Dannie. I will email them and see what they think.

**Comment by stdavis** [comment]
The new data has been wired up for about a week now and everything seems good.
