### ISSUE TITLE
Steps for Prod Release

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#664]
## Deploy
- [x] Point at production ugrc web api
- [x] Run Terraform
- [x] Grant read-only access to the functions service account for the sheet
- [x] Set Secrets & Variables in prod repo env
- [x] Manually create remote config parameters with empty default values
- [x] Update prod spreadsheet to match dev (resolving any differences)
- [x] Deploy app script to sheet
- [x] Run app script in the spreadsheet to update the values
- [x] promote dev to main
- [x] merge release PR
- [x] request security exception for unauthenticated requests to functions and cloud run services (INC0084282)
- [x] Run a search on all layers and see if there are any obvious config spreadsheet issues that can be fixed
- [x] Request DNS change (INC0085588)
- [x] Test

## Clean Up
- [x] forklift updates (https://github.com/agrc/deq-enviro/pull/685)
- [x] Zabbix monitors ([INC0089214](https://workspaces.dts.utah.gov/incident.do?sys_id=595932111b7582506dc92f85624bcbc4&sysparm_record_target=incident&sysparm_record_row=1&sysparm_record_rows=2347&sysparm_record_list=active%3Dtrue%5Ecaller_id%3D43b924538761f150229333f50cbb35f8%5EORopened_by%3D43b924538761f150229333f50cbb35f8%5EORwatch_listCONTAINS43b924538761f150229333f50cbb35f8%5EORbusiness_service%21%3D4bac1f4487480e109ffdfdd8cebb359c%5EORservice_offering%21%3D3fc437c487c80e109ffdfdd8cebb351d%5EORbusiness_service%3D%5EORservice_offering%3D%5EORcaller_id.companyIN%5EORDERBYDESCnumber))
- [x] .net API on mapserv
- [x] web app on mapserv
~- [ ] web services on mapserv~
	~- There are a few query layers that are still being reference by the mapserve service since they are not pushed to AGOL as part of SGID. I'll need to figure this out before deleting the map service.~
	    ~- Dry Clean Facilities~
	   ~- Municipal Separate Storm Sewer System (MS4) Permits~
- [x] gp services on mapserv
- [x] permission proxy (address point editing is the last app using this)
- [x] ravendb database
- [x] remove build_json.py in forklift pallet
- [x] discover prod quad-word regex (result-table-secure-antenna)
- [x] unregister SOE
~- [ ] mapserv test server?~
- [x] [NSX load balancer] (https://docs.google.com/drawings/d/1hqfETVkfn_MTh8sNWp6GFrSx9xsABR3vRNyC7YXMj0E/edit) ([INC0092273](https://workspaces.dts.utah.gov/incident.do?sys_id=8208a3221bb10a506dc92f85624bcbc2&sysparm_record_target=incident&sysparm_record_row=1&sysparm_record_rows=2111&sysparm_record_list=active%3Dtrue%5Ecaller_id%3D43b924538761f150229333f50cbb35f8%5EORopened_by%3D43b924538761f150229333f50cbb35f8%5EORwatch_listCONTAINS43b924538761f150229333f50cbb35f8%5EORbusiness_service%21%3D4bac1f4487480e109ffdfdd8cebb359c%5EORservice_offering%21%3D3fc437c487c80e109ffdfdd8cebb351d%5EORbusiness_service%3D%5EORservice_offering%3D%5EORcaller_id.companyIN%5EORDERBYDESCnumber))

**Comment by nathankota** [comment]
The following task was moved to #533. The rest of the tasks are complete.
>   - [ ] web services on mapserv
>   - There are a few query layers that are still being reference by the mapserve service since they are not pushed to AGOL as part of SGID. I'll need to figure this out before deleting the map service.
>   - Dry Clean Facilities
>   - Municipal Separate Storm Sewer System (MS4) Permits
