### ISSUE TITLE
New data source for DERR > Environmental Incidents

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#665]
The ERSpillsDatabase is to be replaced by the new Environmental Incidents Salesforce app. We can palletjack from SalesForce to DEQ AGOL once the data/views are made available to us from SalesForce. The tables/views forklift currently uses in ERSpills are:

- DEQmap_EnviroIncidents
- vwDryCleaners
- DEQmap_Chemical
- DEQmap_ImpactedMedia

**Comment by stdavis** [comment]
These two spreadsheets will help determine how palletjack gets the data from salesforce. It will likely need to implement some of the business logic that previously was contained in the SQL views.

[DEQMapFileUGRC.xlsx](https://github.com/agrc/deq-enviro/files/15380629/DEQMapFileUGRC.xlsx)

[Spills Table To IM View Mappings.xlsx](https://github.com/agrc/deq-enviro/files/15380620/Spills.Table.To.IM.View.Mappings.xlsx)

I'll ask Barry about getting connected to the salesforce app.

**Comment by stdavis** [comment]
https://github.com/agrc/deq-eid-skid

**Comment by stdavis** [comment]
From Michelle when I asked about the dry cleaners table:
>Dry Cleaners were not added to the Salesforce database. It looks like it is a standalone table, so I am just going to build the layer in GIS online to use for the Interactive Map. I will let you know when completed.

**Comment by stdavis** [comment]
Everything but dry cleaners is done and deployed to production. Michelle is still working on the dry cleaners agol service.

**Comment by stdavis** [comment]
[Dry Cleaner Facilities](https://services2.arcgis.com/NnxP4LZ3zX8wWmP9/arcgis/rest/services/Utah_Dry_Cleaner_Facilities/FeatureServer) has been pushed to AGOL and I've updated the config spreadsheet.

**Comment by steveoh** [comment]
Does that mean that all deq enviro layers are in AGOL and the mapserv service is no longer used?
