### ISSUE TITLE
Update training videos

### ISSUE THREAD

**Issue by nathankota** [agrc/deq-enviro#682]
The training videos link on the right side of the header menu of the new app goes to a [DEQ Training Videos page](https://deq.utah.gov/general/training-videos-interactive-map) that describes the old app. Have DEQ update the videos for the new app.

![image](https://github.com/agrc/deq-enviro/assets/15659642/1875a441-f9a3-4766-9d26-d52bf342540e)

**Comment by stdavis** [comment]
It looks like they have updated their videos.
