### ISSUE TITLE
Add support for searching for addresses that do not show up in Address Point data

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#707]
Michelle reported an issue with a user not being able to find this address: 802 West 100 South, SLC

This is an address that shows up in DEQ data.

To fix this, we could use masquerade for typeahead as well as geocoding addresses that are not found in the address point data.

**Comment by steveoh** [comment]
@gregbunce can we look into this address for geocoding?

**Comment by stdavis** [comment]
I don't think that 802 West 100 South is a good address. I checked in google maps and didn't see it. The closest that I found was 804 W.

**Comment by stdavis** [comment]
I don't think that I was very clear. This is not a geocoding issue. @gregbunce I don't think that there is anything that you need to check on this issue. The project does not geocode at the moment. It just auto-completes using address point data. The fix is for me to add geocoding to this project.

**Comment by stdavis** [comment]
More addresses from Michelle:
>187 North Broadway Avenue, or 187 N Broadway, Tooele or 748 East 400 South, Salt Lake City are not showing up on the Interactive May. They are good addresses.

**Comment by stdavis** [comment]
Yes, that is expected. Currently, this app auto-completes with address points only. It needs to be updated to use masquerade for autocomplete and geocoding if nothing is selected.
